version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "conexa_desafio"
    ports:
      - "3306:3306"
    volumes:
      - /home/angelo/clients/particular/rapid/conexa/docker/volumes:/var/lib/mysql    
 